/**
 * @file seed.ts
 * @description Database seed script for Armory Intelligence
 * 
 * Run with: npx tsx prisma/seed.ts
 */

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// ============================================
// FIREARMS DATA (50 entries)
// ============================================

const firearms = [
  // HANDGUNS
  {
    name: "Glock 19 Gen5",
    manufacturer: "Glock",
    type: "handgun",
    action: "semi-auto",
    caliber: "9mm",
    capacity: 15,
    weight: 1.5,
    barrelLength: 4.02,
    overallLength: 7.36,
    price: 549,
    country: "Austria",
    yearIntroduced: 2017,
    description: "The Glock 19 Gen5 is a compact, versatile 9mm pistol that serves as one of the most popular firearms for concealed carry, duty use, and home defense. Features Glock's Safe Action System and enhanced ergonomics.",
    safetyFeatures: JSON.stringify(["Safe Action System", "Trigger Safety", "Firing Pin Safety", "Drop Safety"]),
  },
  {
    name: "Sig Sauer P320 Compact",
    manufacturer: "Sig Sauer",
    type: "handgun",
    action: "semi-auto",
    caliber: "9mm",
    capacity: 15,
    weight: 1.6,
    barrelLength: 3.9,
    overallLength: 7.2,
    price: 579,
    country: "USA",
    yearIntroduced: 2014,
    description: "The P320 is a modular striker-fired pistol that won the US Military's Modular Handgun System competition. Its serialized trigger group allows users to change calibers and frame sizes easily.",
    safetyFeatures: JSON.stringify(["Striker Safety", "Disconnect Safety", "3-Point Takedown Safety"]),
  },
  {
    name: "Smith & Wesson M&P Shield Plus",
    manufacturer: "Smith & Wesson",
    type: "handgun",
    action: "semi-auto",
    caliber: "9mm",
    capacity: 13,
    weight: 1.28,
    barrelLength: 3.1,
    overallLength: 6.1,
    price: 499,
    country: "USA",
    yearIntroduced: 2021,
    description: "The Shield Plus offers enhanced capacity in a micro-compact frame, making it ideal for concealed carry with 13+1 capacity.",
    safetyFeatures: JSON.stringify(["Internal Striker Safety", "Tactile Trigger Reset"]),
  },
  {
    name: "Springfield Hellcat Pro",
    manufacturer: "Springfield Armory",
    type: "handgun",
    action: "semi-auto",
    caliber: "9mm",
    capacity: 15,
    weight: 1.42,
    barrelLength: 3.7,
    overallLength: 6.6,
    price: 599,
    country: "USA",
    yearIntroduced: 2022,
    description: "The Hellcat Pro bridges the gap between micro-compact and compact with 15-round capacity and excellent ergonomics.",
    safetyFeatures: JSON.stringify(["Loaded Chamber Indicator", "Grip Safety (optional)"]),
  },
  {
    name: "Beretta 92FS",
    manufacturer: "Beretta",
    type: "handgun",
    action: "semi-auto",
    caliber: "9mm",
    capacity: 15,
    weight: 2.13,
    barrelLength: 4.9,
    overallLength: 8.5,
    price: 699,
    country: "Italy",
    yearIntroduced: 1975,
    description: "The legendary M9 service pistol used by US Military for 30+ years. Known for reliability, accuracy, and smooth DA/SA trigger.",
    safetyFeatures: JSON.stringify(["Ambidextrous Safety/Decocker", "Firing Pin Block", "Open Slide Design"]),
  },
  {
    name: "CZ 75 SP-01",
    manufacturer: "CZ",
    type: "handgun",
    action: "semi-auto",
    caliber: "9mm",
    capacity: 18,
    weight: 2.45,
    barrelLength: 4.6,
    overallLength: 8.15,
    price: 699,
    country: "Czech Republic",
    yearIntroduced: 2005,
    description: "Competition-ready duty pistol with exceptional ergonomics and accuracy. Features a steel frame and extended capacity.",
    safetyFeatures: JSON.stringify(["Manual Safety", "Firing Pin Block", "Decocker (on some models)"]),
  },
  {
    name: "Walther PDP Full Size",
    manufacturer: "Walther",
    type: "handgun",
    action: "semi-auto",
    caliber: "9mm",
    capacity: 18,
    weight: 1.76,
    barrelLength: 4.5,
    overallLength: 8.0,
    price: 649,
    country: "Germany",
    yearIntroduced: 2021,
    description: "The Performance Duty Pistol features one of the best factory triggers and an optic-ready slide.",
    safetyFeatures: JSON.stringify(["Trigger Safety", "Internal Striker Block", "Superterrain Serrations"]),
  },
  {
    name: "HK VP9",
    manufacturer: "Heckler & Koch",
    type: "handgun",
    action: "semi-auto",
    caliber: "9mm",
    capacity: 17,
    weight: 1.69,
    barrelLength: 4.09,
    overallLength: 7.34,
    price: 719,
    country: "Germany",
    yearIntroduced: 2014,
    description: "German engineering meets striker-fired reliability. Known for exceptional ergonomics and crisp trigger.",
    safetyFeatures: JSON.stringify(["Trigger Safety", "Firing Pin Block", "Disassembly Safety"]),
  },
  {
    name: "Ruger SR1911",
    manufacturer: "Ruger",
    type: "handgun",
    action: "semi-auto",
    caliber: ".45 ACP",
    capacity: 8,
    weight: 2.44,
    barrelLength: 5.0,
    overallLength: 8.67,
    price: 939,
    country: "USA",
    yearIntroduced: 2011,
    description: "Classic 1911 design with modern manufacturing. Perfect blend of tradition and reliability.",
    safetyFeatures: JSON.stringify(["Manual Thumb Safety", "Grip Safety", "Series 70 Firing System"]),
  },
  {
    name: "Smith & Wesson 686 Plus",
    manufacturer: "Smith & Wesson",
    type: "handgun",
    action: "revolver",
    caliber: ".357 Magnum",
    capacity: 7,
    weight: 2.5,
    barrelLength: 4.0,
    overallLength: 9.56,
    price: 899,
    country: "USA",
    yearIntroduced: 1980,
    description: "Premium stainless steel revolver with 7-shot capacity. Excellent for home defense and hunting.",
    safetyFeatures: JSON.stringify(["Internal Lock", "Transfer Bar"]),
  },
  {
    name: "Ruger GP100",
    manufacturer: "Ruger",
    type: "handgun",
    action: "revolver",
    caliber: ".357 Magnum",
    capacity: 6,
    weight: 2.5,
    barrelLength: 4.2,
    overallLength: 9.5,
    price: 829,
    country: "USA",
    yearIntroduced: 1985,
    description: "Built like a tank, the GP100 handles magnum loads with ease. Triple-locking cylinder for strength.",
    safetyFeatures: JSON.stringify(["Transfer Bar Safety", "Triple-Locking Cylinder"]),
  },
  {
    name: "Glock 43X",
    manufacturer: "Glock",
    type: "handgun",
    action: "semi-auto",
    caliber: "9mm",
    capacity: 10,
    weight: 1.26,
    barrelLength: 3.41,
    overallLength: 6.5,
    price: 549,
    country: "Austria",
    yearIntroduced: 2019,
    description: "Slim and concealable with enhanced grip for better control. Perfect for everyday carry.",
    safetyFeatures: JSON.stringify(["Safe Action System", "Trigger Safety", "Firing Pin Safety"]),
  },
  {
    name: "FN 509 Tactical",
    manufacturer: "FN Herstal",
    type: "handgun",
    action: "semi-auto",
    caliber: "9mm",
    capacity: 24,
    weight: 1.81,
    barrelLength: 4.5,
    overallLength: 8.0,
    price: 999,
    country: "Belgium",
    yearIntroduced: 2018,
    description: "Tactical-ready pistol with threaded barrel, optic-ready slide, and high capacity magazines.",
    safetyFeatures: JSON.stringify(["Low-Profile Optics Mounting", "Suppressor-Height Sights"]),
  },

  // RIFLES
  {
    name: "Smith & Wesson M&P15 Sport II",
    manufacturer: "Smith & Wesson",
    type: "rifle",
    action: "semi-auto",
    caliber: "5.56 NATO/.223",
    capacity: 30,
    weight: 6.5,
    barrelLength: 16.0,
    overallLength: 35.0,
    price: 749,
    country: "USA",
    yearIntroduced: 2016,
    description: "Affordable, reliable AR-15 platform rifle. Great entry point for sport shooting and home defense.",
    safetyFeatures: JSON.stringify(["Safety Selector", "Bolt Catch", "Dust Cover"]),
  },
  {
    name: "Ruger AR-556",
    manufacturer: "Ruger",
    type: "rifle",
    action: "semi-auto",
    caliber: "5.56 NATO/.223",
    capacity: 30,
    weight: 6.5,
    barrelLength: 16.1,
    overallLength: 32.25,
    price: 799,
    country: "USA",
    yearIntroduced: 2015,
    description: "Ruger's take on the AR-15 with cold hammer-forged barrel and reliable gas system.",
    safetyFeatures: JSON.stringify(["Safety Selector", "Forward Assist", "Dust Cover"]),
  },
  {
    name: "Daniel Defense DDM4 V7",
    manufacturer: "Daniel Defense",
    type: "rifle",
    action: "semi-auto",
    caliber: "5.56 NATO/.223",
    capacity: 30,
    weight: 6.53,
    barrelLength: 16.0,
    overallLength: 32.75,
    price: 1899,
    country: "USA",
    yearIntroduced: 2015,
    description: "Premium AR-15 with cold hammer-forged barrel, M-LOK rail, and exceptional build quality.",
    safetyFeatures: JSON.stringify(["Ambidextrous Safety", "Enhanced Trigger Guard"]),
  },
  {
    name: "Springfield SAINT Victor",
    manufacturer: "Springfield Armory",
    type: "rifle",
    action: "semi-auto",
    caliber: "5.56 NATO/.223",
    capacity: 30,
    weight: 6.9,
    barrelLength: 16.0,
    overallLength: 34.5,
    price: 1199,
    country: "USA",
    yearIntroduced: 2019,
    description: "Mid-tier AR-15 with premium features including Melonite-finished barrel and Bravo Company furniture.",
    safetyFeatures: JSON.stringify(["Accu-Tite Tension System", "Enhanced Trigger"]),
  },
  {
    name: "Ruger 10/22 Carbine",
    manufacturer: "Ruger",
    type: "rifle",
    action: "semi-auto",
    caliber: ".22 LR",
    capacity: 10,
    weight: 5.0,
    barrelLength: 18.5,
    overallLength: 37.0,
    price: 309,
    country: "USA",
    yearIntroduced: 1964,
    description: "America's favorite rimfire rifle. Perfect for training, plinking, and small game hunting.",
    safetyFeatures: JSON.stringify(["Cross-Bolt Safety", "Bolt Lock"]),
  },
  {
    name: "Marlin Model 60",
    manufacturer: "Marlin",
    type: "rifle",
    action: "semi-auto",
    caliber: ".22 LR",
    capacity: 14,
    weight: 5.5,
    barrelLength: 19.0,
    overallLength: 37.5,
    price: 219,
    country: "USA",
    yearIntroduced: 1960,
    description: "Classic tube-fed semi-auto with smooth action. World's most popular .22 rifle.",
    safetyFeatures: JSON.stringify(["Cross-Bolt Safety", "Last Shot Hold Open"]),
  },
  {
    name: "Remington 700 SPS",
    manufacturer: "Remington",
    type: "rifle",
    action: "bolt",
    caliber: ".308 Winchester",
    capacity: 4,
    weight: 7.5,
    barrelLength: 24.0,
    overallLength: 43.6,
    price: 779,
    country: "USA",
    yearIntroduced: 1962,
    description: "The most accurate factory rifle ever made. Gold standard for bolt-action hunting rifles.",
    safetyFeatures: JSON.stringify(["3-Position Safety", "X-Mark Pro Trigger"]),
  },
  {
    name: "Savage Axis II XP",
    manufacturer: "Savage",
    type: "rifle",
    action: "bolt",
    caliber: ".308 Winchester",
    capacity: 4,
    weight: 6.5,
    barrelLength: 22.0,
    overallLength: 43.88,
    price: 449,
    country: "USA",
    yearIntroduced: 2019,
    description: "Budget-friendly bolt action with AccuTrigger. Great starter hunting rifle with included scope.",
    safetyFeatures: JSON.stringify(["2-Position Safety", "AccuTrigger"]),
  },
  {
    name: "Ruger American Rifle",
    manufacturer: "Ruger",
    type: "rifle",
    action: "bolt",
    caliber: ".308 Winchester",
    capacity: 4,
    weight: 6.12,
    barrelLength: 22.0,
    overallLength: 42.0,
    price: 499,
    country: "USA",
    yearIntroduced: 2012,
    description: "Modern bolt action with Power Bedding system and Ruger Marksman Adjustable trigger.",
    safetyFeatures: JSON.stringify(["Tang Safety", "Marksman Adjustable Trigger"]),
  },
  {
    name: "Tikka T3x Lite",
    manufacturer: "Tikka",
    type: "rifle",
    action: "bolt",
    caliber: ".308 Winchester",
    capacity: 3,
    weight: 6.0,
    barrelLength: 22.4,
    overallLength: 42.5,
    price: 899,
    country: "Finland",
    yearIntroduced: 2016,
    description: "Finnish precision with butter-smooth bolt and match-grade accuracy out of the box.",
    safetyFeatures: JSON.stringify(["Two-Position Safety", "Total Control Latch"]),
  },
  {
    name: "Browning X-Bolt Hunter",
    manufacturer: "Browning",
    type: "rifle",
    action: "bolt",
    caliber: ".30-06 Springfield",
    capacity: 4,
    weight: 6.8,
    barrelLength: 22.0,
    overallLength: 42.75,
    price: 1099,
    country: "Japan",
    yearIntroduced: 2008,
    description: "Premium hunting rifle with adjustable Feather Trigger and 60-degree bolt throw.",
    safetyFeatures: JSON.stringify(["Tang Safety", "Bolt Unlock Button"]),
  },
  {
    name: "Winchester Model 70 Featherweight",
    manufacturer: "Winchester",
    type: "rifle",
    action: "bolt",
    caliber: ".270 Winchester",
    capacity: 5,
    weight: 6.75,
    barrelLength: 22.0,
    overallLength: 42.75,
    price: 1069,
    country: "USA",
    yearIntroduced: 1936,
    description: "The Rifleman's Rifle returns with controlled round feeding and MOA accuracy guarantee.",
    safetyFeatures: JSON.stringify(["3-Position Safety", "Pre-64 Style Extractor"]),
  },
  {
    name: "Henry Big Boy",
    manufacturer: "Henry",
    type: "rifle",
    action: "lever",
    caliber: ".357 Magnum/.38 Special",
    capacity: 10,
    weight: 8.68,
    barrelLength: 20.0,
    overallLength: 38.5,
    price: 979,
    country: "USA",
    yearIntroduced: 2006,
    description: "Beautiful brass-receiver lever action. American-made quality with smooth action.",
    safetyFeatures: JSON.stringify(["Transfer Bar Safety", "Rebounding Hammer"]),
  },
  {
    name: "Marlin 336",
    manufacturer: "Marlin",
    type: "rifle",
    action: "lever",
    caliber: ".30-30 Winchester",
    capacity: 6,
    weight: 7.0,
    barrelLength: 20.0,
    overallLength: 38.5,
    price: 689,
    country: "USA",
    yearIntroduced: 1948,
    description: "Classic deer rifle that has taken more whitetails than any other. Side-ejection for easy scope mounting.",
    safetyFeatures: JSON.stringify(["Half-Cock Safety", "Rebounding Hammer"]),
  },
  {
    name: "AERO Precision M4E1",
    manufacturer: "Aero Precision",
    type: "rifle",
    action: "semi-auto",
    caliber: "5.56 NATO/.223",
    capacity: 30,
    weight: 6.7,
    barrelLength: 16.0,
    overallLength: 32.5,
    price: 999,
    country: "USA",
    yearIntroduced: 2017,
    description: "Quality-built AR-15 with enhanced upper receiver and precision barrel.",
    safetyFeatures: JSON.stringify(["Ambidextrous Safety", "Enhanced Bolt Catch"]),
  },
  {
    name: "IWI Tavor X95",
    manufacturer: "IWI",
    type: "rifle",
    action: "semi-auto",
    caliber: "5.56 NATO/.223",
    capacity: 30,
    weight: 7.9,
    barrelLength: 16.5,
    overallLength: 26.1,
    price: 1999,
    country: "Israel",
    yearIntroduced: 2016,
    description: "Bullpup design offers full-length barrel in compact package. Israeli military proven.",
    safetyFeatures: JSON.stringify(["Ambidextrous Controls", "Integral Dust Cover"]),
  },

  // SHOTGUNS
  {
    name: "Mossberg 500",
    manufacturer: "Mossberg",
    type: "shotgun",
    action: "pump",
    caliber: "12 Gauge",
    capacity: 6,
    weight: 7.5,
    barrelLength: 18.5,
    overallLength: 38.5,
    price: 419,
    country: "USA",
    yearIntroduced: 1961,
    description: "Time-tested pump action trusted by military, police, and civilians for over 60 years.",
    safetyFeatures: JSON.stringify(["Tang Safety", "Dual Extractors", "Anti-Jam Elevator"]),
  },
  {
    name: "Remington 870 Express",
    manufacturer: "Remington",
    type: "shotgun",
    action: "pump",
    caliber: "12 Gauge",
    capacity: 4,
    weight: 7.25,
    barrelLength: 18.0,
    overallLength: 38.5,
    price: 399,
    country: "USA",
    yearIntroduced: 1950,
    description: "The most popular shotgun ever made with over 11 million sold. Reliable and versatile.",
    safetyFeatures: JSON.stringify(["Cross-Bolt Safety", "Steel Receiver"]),
  },
  {
    name: "Benelli M4",
    manufacturer: "Benelli",
    type: "shotgun",
    action: "semi-auto",
    caliber: "12 Gauge",
    capacity: 5,
    weight: 7.8,
    barrelLength: 18.5,
    overallLength: 40.0,
    price: 1999,
    country: "Italy",
    yearIntroduced: 1998,
    description: "Military-grade semi-auto with ARGO gas system. Used by US Marines and elite units worldwide.",
    safetyFeatures: JSON.stringify(["Cross-Bolt Safety", "Rotating Bolt Head"]),
  },
  {
    name: "Beretta 1301 Tactical",
    manufacturer: "Beretta",
    type: "shotgun",
    action: "semi-auto",
    caliber: "12 Gauge",
    capacity: 5,
    weight: 6.7,
    barrelLength: 18.5,
    overallLength: 37.8,
    price: 1499,
    country: "Italy",
    yearIntroduced: 2015,
    description: "Fastest cycling semi-auto shotgun. BLINK gas system cycles in 36% less time.",
    safetyFeatures: JSON.stringify(["Cross-Bolt Safety", "Oversized Controls"]),
  },
  {
    name: "Mossberg 590A1",
    manufacturer: "Mossberg",
    type: "shotgun",
    action: "pump",
    caliber: "12 Gauge",
    capacity: 9,
    weight: 7.25,
    barrelLength: 20.0,
    overallLength: 41.0,
    price: 599,
    country: "USA",
    yearIntroduced: 1987,
    description: "Military-spec 500 with heavy barrel, metal trigger guard, and bayonet lug. MIL-SPEC 3443E compliant.",
    safetyFeatures: JSON.stringify(["Tang Safety", "Heavy-Wall Barrel", "Metal Trigger Guard"]),
  },
  {
    name: "Winchester SXP Defender",
    manufacturer: "Winchester",
    type: "shotgun",
    action: "pump",
    caliber: "12 Gauge",
    capacity: 5,
    weight: 6.62,
    barrelLength: 18.0,
    overallLength: 38.5,
    price: 349,
    country: "Turkey",
    yearIntroduced: 2009,
    description: "Inertia-assisted pump action for faster cycling. Rotary bolt for strength.",
    safetyFeatures: JSON.stringify(["Cross-Bolt Safety", "Rotary Bolt"]),
  },
  {
    name: "Stoeger M3000",
    manufacturer: "Stoeger",
    type: "shotgun",
    action: "semi-auto",
    caliber: "12 Gauge",
    capacity: 4,
    weight: 7.3,
    barrelLength: 18.5,
    overallLength: 39.5,
    price: 649,
    country: "Turkey",
    yearIntroduced: 2013,
    description: "Affordable inertia-driven semi-auto. Benelli quality at budget price.",
    safetyFeatures: JSON.stringify(["Cross-Bolt Safety", "Inertia Driven"]),
  },
  {
    name: "Browning Citori 725",
    manufacturer: "Browning",
    type: "shotgun",
    action: "break",
    caliber: "12 Gauge",
    capacity: 2,
    weight: 7.5,
    barrelLength: 28.0,
    overallLength: 45.0,
    price: 2669,
    country: "Japan",
    yearIntroduced: 2012,
    description: "Premium over/under for sporting clays and hunting. Fire Lite mechanical trigger system.",
    safetyFeatures: JSON.stringify(["Top Tang Safety", "Automatic Ejectors"]),
  },
  {
    name: "CZ Drake",
    manufacturer: "CZ",
    type: "shotgun",
    action: "break",
    caliber: "12 Gauge",
    capacity: 2,
    weight: 7.5,
    barrelLength: 28.0,
    overallLength: 46.0,
    price: 699,
    country: "Turkey",
    yearIntroduced: 2016,
    description: "Affordable over/under with Turkish walnut and single selective trigger.",
    safetyFeatures: JSON.stringify(["Top Tang Safety", "Manual Extractors"]),
  },
  {
    name: "Kel-Tec KSG",
    manufacturer: "Kel-Tec",
    type: "shotgun",
    action: "pump",
    caliber: "12 Gauge",
    capacity: 14,
    weight: 6.9,
    barrelLength: 18.5,
    overallLength: 26.1,
    price: 799,
    country: "USA",
    yearIntroduced: 2011,
    description: "Bullpup pump with dual magazine tubes. 14+1 capacity in ultra-compact package.",
    safetyFeatures: JSON.stringify(["Cross-Bolt Safety", "Dual Tube Selector"]),
  },

  // Additional firearms to reach 50
  {
    name: "Glock 17 Gen5",
    manufacturer: "Glock",
    type: "handgun",
    action: "semi-auto",
    caliber: "9mm",
    capacity: 17,
    weight: 1.65,
    barrelLength: 4.49,
    overallLength: 7.95,
    price: 549,
    country: "Austria",
    yearIntroduced: 2017,
    description: "Full-size duty pistol and the original Glock design. Standard for law enforcement worldwide.",
    safetyFeatures: JSON.stringify(["Safe Action System", "Trigger Safety", "Firing Pin Safety"]),
  },
  {
    name: "SIG P365",
    manufacturer: "Sig Sauer",
    type: "handgun",
    action: "semi-auto",
    caliber: "9mm",
    capacity: 10,
    weight: 1.0,
    barrelLength: 3.1,
    overallLength: 5.8,
    price: 579,
    country: "USA",
    yearIntroduced: 2018,
    description: "Revolutionary micro-compact with 10+1 capacity. Changed the concealed carry market.",
    safetyFeatures: JSON.stringify(["Striker Safety", "Disconnect Safety"]),
  },
  {
    name: "Glock 45",
    manufacturer: "Glock",
    type: "handgun",
    action: "semi-auto",
    caliber: "9mm",
    capacity: 17,
    weight: 1.55,
    barrelLength: 4.02,
    overallLength: 7.44,
    price: 549,
    country: "Austria",
    yearIntroduced: 2018,
    description: "Crossover pistol combining G19 slide with G17 frame. Perfect balance of size and capacity.",
    safetyFeatures: JSON.stringify(["Safe Action System", "Trigger Safety", "Firing Pin Safety"]),
  },
  {
    name: "CZ P-10 C",
    manufacturer: "CZ",
    type: "handgun",
    action: "semi-auto",
    caliber: "9mm",
    capacity: 15,
    weight: 1.63,
    barrelLength: 4.02,
    overallLength: 7.3,
    price: 499,
    country: "Czech Republic",
    yearIntroduced: 2017,
    description: "CZ's striker-fired answer to the Glock. Exceptional trigger and ergonomics.",
    safetyFeatures: JSON.stringify(["Trigger Safety", "Striker Block"]),
  },
  {
    name: "Kimber Custom II",
    manufacturer: "Kimber",
    type: "handgun",
    action: "semi-auto",
    caliber: ".45 ACP",
    capacity: 7,
    weight: 2.44,
    barrelLength: 5.0,
    overallLength: 8.7,
    price: 899,
    country: "USA",
    yearIntroduced: 1996,
    description: "Premium 1911 with match-grade barrel and aluminum match trigger.",
    safetyFeatures: JSON.stringify(["Manual Safety", "Grip Safety", "Firing Pin Block"]),
  },
  {
    name: "Smith & Wesson M&P9 M2.0",
    manufacturer: "Smith & Wesson",
    type: "handgun",
    action: "semi-auto",
    caliber: "9mm",
    capacity: 17,
    weight: 1.56,
    barrelLength: 4.25,
    overallLength: 7.4,
    price: 569,
    country: "USA",
    yearIntroduced: 2017,
    description: "Second generation M&P with improved trigger, grip texture, and barrel.",
    safetyFeatures: JSON.stringify(["Internal Chassis", "Tactile Trigger Reset"]),
  },
  {
    name: "FN Five-seveN",
    manufacturer: "FN Herstal",
    type: "handgun",
    action: "semi-auto",
    caliber: "5.7x28mm",
    capacity: 20,
    weight: 1.43,
    barrelLength: 4.8,
    overallLength: 8.2,
    price: 1499,
    country: "Belgium",
    yearIntroduced: 1998,
    description: "Futuristic pistol firing high-velocity 5.7x28mm. Low recoil with 20-round capacity.",
    safetyFeatures: JSON.stringify(["Manual Safety", "Magazine Disconnect"]),
  },
  {
    name: "PSA AR-15",
    manufacturer: "Palmetto State Armory",
    type: "rifle",
    action: "semi-auto",
    caliber: "5.56 NATO/.223",
    capacity: 30,
    weight: 6.5,
    barrelLength: 16.0,
    overallLength: 32.5,
    price: 499,
    country: "USA",
    yearIntroduced: 2015,
    description: "Budget-friendly AR-15 that doesn't sacrifice reliability. Best value in the market.",
    safetyFeatures: JSON.stringify(["Safety Selector", "Forward Assist", "Dust Cover"]),
  },
];

// ============================================
// SAFETY CHECKLISTS
// ============================================

const safetyChecklists = [
  {
    category: "storage",
    title: "Home Firearm Storage Safety",
    description: "Essential safety checklist for storing firearms at home, especially with children present",
    priority: "critical",
    audience: "all",
    items: JSON.stringify([
      { id: "s1", text: "Verify all firearms are unloaded before storage", priority: "critical", note: "Check chamber twice" },
      { id: "s2", text: "Store in a locked safe or security cabinet", priority: "critical" },
      { id: "s3", text: "Keep ammunition separate from firearms", priority: "high" },
      { id: "s4", text: "Use cable locks or trigger locks as secondary security", priority: "high" },
      { id: "s5", text: "Store keys/combinations in a secure, separate location", priority: "high" },
      { id: "s6", text: "Bolt safe to floor or wall", priority: "medium" },
      { id: "s7", text: "Use dehumidifier or desiccants in safe", priority: "medium" },
      { id: "s8", text: "Maintain inventory list", priority: "low" },
    ]),
  },
  {
    category: "cleaning",
    title: "Firearm Cleaning Safety Protocol",
    description: "Step-by-step safety checklist before and during firearm maintenance",
    priority: "critical",
    audience: "all",
    items: JSON.stringify([
      { id: "c1", text: "Remove magazine and verify chamber is EMPTY", priority: "critical", note: "Check twice visually and physically" },
      { id: "c2", text: "Point firearm in safe direction at all times", priority: "critical" },
      { id: "c3", text: "Remove ALL ammunition from work area", priority: "critical" },
      { id: "c4", text: "Work in well-ventilated area", priority: "high", note: "Solvents produce harmful fumes" },
      { id: "c5", text: "Wear safety glasses", priority: "high" },
      { id: "c6", text: "Use proper cleaning chemicals only", priority: "medium" },
      { id: "c7", text: "Inspect for wear or damage during cleaning", priority: "medium" },
      { id: "c8", text: "Function check after reassembly (unloaded)", priority: "high" },
    ]),
  },
  {
    category: "range",
    title: "Range Safety Rules",
    description: "Essential safety rules for every range visit",
    priority: "critical",
    audience: "all",
    items: JSON.stringify([
      { id: "r1", text: "Always keep firearm pointed downrange", priority: "critical" },
      { id: "r2", text: "Keep finger off trigger until ready to fire", priority: "critical" },
      { id: "r3", text: "Wear eye and ear protection at all times", priority: "critical" },
      { id: "r4", text: "Treat every firearm as if it's loaded", priority: "critical" },
      { id: "r5", text: "Know and obey all range commands", priority: "high" },
      { id: "r6", text: "Only load when on the firing line", priority: "high" },
      { id: "r7", text: "Unload and show clear when called", priority: "high" },
      { id: "r8", text: "Never handle firearms during cease fire", priority: "critical" },
    ]),
  },
  {
    category: "transport",
    title: "Firearm Transport Safety",
    description: "Safe transport guidelines for vehicle and travel",
    priority: "high",
    audience: "all",
    items: JSON.stringify([
      { id: "t1", text: "Unload all firearms before transport", priority: "critical" },
      { id: "t2", text: "Use a locked case or container", priority: "high" },
      { id: "t3", text: "Store ammunition separately", priority: "high" },
      { id: "t4", text: "Place in trunk or area not accessible from passenger compartment", priority: "high" },
      { id: "t5", text: "Know destination state/local laws", priority: "critical", note: "Laws vary significantly" },
      { id: "t6", text: "Keep documentation accessible", priority: "medium" },
      { id: "t7", text: "Never leave unattended in vehicle", priority: "high" },
    ]),
  },
];

// ============================================
// HISTORICAL ERAS
// ============================================

const historicalEras = [
  {
    name: "The Birth of Gunpowder",
    startYear: 850,
    endYear: 1350,
    order: 1,
    description: "Gunpowder invented in China spreads to Europe via the Silk Road, leading to the first primitive firearms.",
    keyEvents: JSON.stringify([
      "850 AD: Chinese alchemists discover gunpowder",
      "1132: First fire lance used in China",
      "1260: First hand cannons appear in Europe",
      "1326: First illustrated firearm in Europe (Walter de Milemete manuscript)",
    ]),
    innovations: JSON.stringify(["Gunpowder formula", "Fire lance", "Hand cannon"]),
  },
  {
    name: "Matchlock Era",
    startYear: 1350,
    endYear: 1550,
    order: 2,
    description: "The matchlock mechanism revolutionizes warfare, allowing soldiers to aim while firing.",
    keyEvents: JSON.stringify([
      "1411: First matchlock mechanism developed",
      "1453: Firearms help Ottoman Turks conquer Constantinople",
      "1503: Spanish tercios use arquebuses effectively at Cerignola",
    ]),
    innovations: JSON.stringify(["Matchlock ignition", "Arquebus", "Musket"]),
  },
  {
    name: "Wheellock & Flintlock",
    startYear: 1550,
    endYear: 1840,
    order: 3,
    description: "Self-igniting mechanisms make firearms practical for cavalry and everyday carry.",
    keyEvents: JSON.stringify([
      "1509: Wheellock invented in Germany",
      "1610: Flintlock developed in France",
      "1776: American Revolution fought with flintlocks",
      "1807: Percussion cap invented",
    ]),
    innovations: JSON.stringify(["Wheellock", "Flintlock", "Percussion cap", "Rifled barrel"]),
  },
  {
    name: "Percussion & Cartridge Revolution",
    startYear: 1840,
    endYear: 1890,
    order: 4,
    description: "Self-contained metallic cartridges transform firearm design and reliability.",
    keyEvents: JSON.stringify([
      "1847: Colt Walker revolver",
      "1860: Spencer repeating rifle in Civil War",
      "1873: Winchester Model 1873 'Gun That Won the West'",
      "1886: First smokeless powder cartridge",
    ]),
    innovations: JSON.stringify(["Metallic cartridge", "Repeating rifle", "Revolver", "Smokeless powder"]),
  },
  {
    name: "Semi-Automatic Age",
    startYear: 1890,
    endYear: 1945,
    order: 5,
    description: "Self-loading mechanisms enable rapid fire and change warfare forever.",
    keyEvents: JSON.stringify([
      "1893: Borchardt C-93 first practical semi-auto pistol",
      "1911: John Browning's 1911 adopted by US Military",
      "1936: M1 Garand becomes first standard-issue semi-auto rifle",
      "1944: StG 44 creates assault rifle category",
    ]),
    innovations: JSON.stringify(["Semi-automatic action", "Detachable magazine", "Assault rifle concept"]),
  },
  {
    name: "Modern Firearms Era",
    startYear: 1945,
    endYear: 2000,
    order: 6,
    description: "Polymer frames, striker-fired actions, and modular designs become standard.",
    keyEvents: JSON.stringify([
      "1959: AR-15/M16 developed by Eugene Stoner",
      "1963: First polymer-framed pistol (H&K VP70)",
      "1982: Glock 17 introduces polymer frame mainstream",
      "1994: Picatinny rail standardized",
    ]),
    innovations: JSON.stringify(["Polymer frame", "Striker-fired action", "Modular rail systems", "Red dot sights"]),
  },
];

// ============================================
// SEED FUNCTION
// ============================================

async function main() {
  console.log("🔫 Seeding Armory Intelligence database...\n");

  // Clear existing data
  console.log("Clearing existing data...");
  await prisma.firearm.deleteMany();
  await prisma.safetyChecklist.deleteMany();
  await prisma.historicalEra.deleteMany();

  // Seed firearms
  console.log(`\nSeeding ${firearms.length} firearms...`);
  for (const firearm of firearms) {
    await prisma.firearm.create({ data: firearm });
    process.stdout.write(".");
  }
  console.log(" Done!");

  // Seed safety checklists
  console.log(`\nSeeding ${safetyChecklists.length} safety checklists...`);
  for (const checklist of safetyChecklists) {
    await prisma.safetyChecklist.create({ data: checklist });
    process.stdout.write(".");
  }
  console.log(" Done!");

  // Seed historical eras
  console.log(`\nSeeding ${historicalEras.length} historical eras...`);
  for (const era of historicalEras) {
    await prisma.historicalEra.create({ data: era });
    process.stdout.write(".");
  }
  console.log(" Done!");

  console.log("\n✅ Database seeded successfully!");
  console.log(`   - ${firearms.length} firearms`);
  console.log(`   - ${safetyChecklists.length} safety checklists`);
  console.log(`   - ${historicalEras.length} historical eras`);
}

main()
  .catch((e) => {
    console.error("❌ Seed error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
