/**
 * @file weapons-data.ts
 * @description Arsenal Nexus - Complete weapons database
 * Contains both real-world and Star Wars weapons with cross-references
 * 
 * Each sci-fi weapon is mapped to a real-world equivalent for comparison.
 */

import type { Weapon } from "./database.types";

export type WeaponSeed = Omit<Weapon, "id" | "created_at" | "updated_at" | "real_world_equivalent_id"> & {
  _matchKey: string; // internal key for cross-referencing
  _equivalentKey?: string; // matches a real weapon's _matchKey
  imageUrl?: string; // path to weapon image
};

// ============================================
// REAL-WORLD WEAPONS
// ============================================
export const realWeapons: WeaponSeed[] = [
  {
    _matchKey: "m4-carbine",
    name: "M4A1 Carbine",
    universe: "real",
    category: "rifle",
    manufacturer: "Colt Defense",
    era: "Modern (1994–present)",
    description: "Standard-issue US military carbine. Lightweight, gas-operated, select-fire. The backbone of modern infantry.",
    weight_kg: 3.4,
    effective_range_m: 500,
    rate_of_fire: 700,
    damage_rating: 72,
    caliber: "5.56×45mm NATO",
    muzzle_velocity_ms: 910,
    capacity: 30,
    price_usd: 1200,
    action_type: "Gas-operated rotating bolt",
    tactical_score: 85,
    coolness_factor: 70,
    community_rating: 4.3,
    total_votes: 156,
    imageUrl: "/images/weapons/m4a1-carbine.jpg",
    comparison_notes: "Standard against which the E-11 Blaster is compared. Both are standard-issue infantry weapons.",
  },
  {
    _matchKey: "m16a4",
    name: "M16A4 Rifle",
    universe: "real",
    category: "rifle",
    manufacturer: "FN Herstal",
    era: "Modern (1967–present)",
    description: "Full-length service rifle of the US Armed Forces. Longer barrel than M4, better accuracy at range. Legendary platform.",
    weight_kg: 3.9,
    effective_range_m: 550,
    rate_of_fire: 800,
    damage_rating: 75,
    caliber: "5.56×45mm NATO",
    muzzle_velocity_ms: 960,
    capacity: 30,
    price_usd: 1100,
    action_type: "Gas-operated rotating bolt",
    tactical_score: 82,
    coolness_factor: 65,
    community_rating: 4.1,
    total_votes: 134,
    imageUrl: "/images/weapons/m16a4-rifle.jpg",
    comparison_notes: "Comparable to DC-15A - both are full-size service rifles for disciplined military forces.",
  },
  {
    _matchKey: "44-magnum",
    name: ".44 Magnum (S&W Model 29)",
    universe: "real",
    category: "handgun",
    manufacturer: "Smith & Wesson",
    era: "Modern (1955–present)",
    description: "\"The most powerful handgun in the world\" — Dirty Harry. Massive stopping power, iconic six-shooter.",
    weight_kg: 1.3,
    effective_range_m: 50,
    rate_of_fire: 12,
    damage_rating: 82,
    caliber: ".44 Remington Magnum",
    muzzle_velocity_ms: 440,
    capacity: 6,
    price_usd: 1100,
    action_type: "Double-action revolver",
    tactical_score: 55,
    coolness_factor: 92,
    community_rating: 4.6,
    total_votes: 201,
    imageUrl: "/images/weapons/44-magnum.jpg",
    comparison_notes: "Han Solo's DL-44 is literally named after this caliber. Both are iconic 'outlaw' sidearms.",
  },
  {
    _matchKey: "glock-19",
    name: "Glock 19 Gen5",
    universe: "real",
    category: "handgun",
    manufacturer: "Glock",
    era: "Modern (1988–present)",
    description: "The world's most popular compact pistol. Reliable, lightweight, used by military and police worldwide. Perfection.",
    weight_kg: 0.63,
    effective_range_m: 50,
    rate_of_fire: 40,
    damage_rating: 58,
    caliber: "9×19mm Parabellum",
    muzzle_velocity_ms: 375,
    capacity: 15,
    price_usd: 549,
    action_type: "Short recoil, locked breech",
    tactical_score: 78,
    coolness_factor: 55,
    community_rating: 4.4,
    total_votes: 189,
    imageUrl: "/images/weapons/glock-19.jpg",
    comparison_notes: "Comparable to SE-14C - both are compact, reliable sidearms for versatile use.",
  },
  {
    _matchKey: "barrett-m82",
    name: "Barrett M82A1",
    universe: "real",
    category: "sniper",
    manufacturer: "Barrett Firearms",
    era: "Modern (1982–present)",
    description: "Anti-materiel rifle. Can penetrate armored vehicles, concrete walls, and aircraft. The original 'Light Fifty'.",
    weight_kg: 14.0,
    effective_range_m: 1800,
    rate_of_fire: 10,
    damage_rating: 98,
    caliber: ".50 BMG (12.7×99mm)",
    muzzle_velocity_ms: 890,
    capacity: 10,
    price_usd: 8900,
    action_type: "Short recoil, rotating bolt",
    tactical_score: 70,
    coolness_factor: 95,
    community_rating: 4.8,
    total_votes: 223,
    imageUrl: "/images/weapons/barrett-m82.jpg",
    comparison_notes: "The closest real-world equivalent to Boba Fett's EE-3 - both are precision weapons for bounty hunters.",
  },
  {
    _matchKey: "m2-browning",
    name: "M2 Browning .50 Cal",
    universe: "real",
    category: "heavy",
    manufacturer: "General Dynamics",
    era: "1933–present",
    description: "\"Ma Deuce\" - The longest-serving firearm in US military history (90+ years). Vehicle-mounted heavy machine gun.",
    weight_kg: 38.0,
    effective_range_m: 1800,
    rate_of_fire: 550,
    damage_rating: 95,
    caliber: ".50 BMG",
    muzzle_velocity_ms: 890,
    capacity: 100,
    price_usd: 16000,
    action_type: "Short recoil, belt-fed",
    tactical_score: 90,
    coolness_factor: 85,
    community_rating: 4.7,
    total_votes: 178,
    imageUrl: "/images/weapons/m2-browning.jpg",
    comparison_notes: "Direct equivalent to the E-Web Heavy Repeating Blaster - both are emplaced crew-served weapons.",
  },
  {
    _matchKey: "mossberg-500",
    name: "Mossberg 500",
    universe: "real",
    category: "shotgun",
    manufacturer: "Mossberg",
    era: "Modern (1961–present)",
    description: "The most versatile pump-action shotgun ever made. Used for home defense, hunting, and military. US military MIL-SPEC qualified.",
    weight_kg: 3.4,
    effective_range_m: 40,
    rate_of_fire: 15,
    damage_rating: 78,
    caliber: "12 Gauge",
    muzzle_velocity_ms: 400,
    capacity: 6,
    price_usd: 419,
    action_type: "Pump-action",
    tactical_score: 72,
    coolness_factor: 68,
    community_rating: 4.3,
    total_votes: 145,
    imageUrl: "/images/weapons/mossberg-500.jpg",
    comparison_notes: "Similar role to Wookiee Bowcaster - both are powerful close-range weapons favored by warriors.",
  },
  {
    _matchKey: "javelin",
    name: "FGM-148 Javelin",
    universe: "real",
    category: "explosive",
    manufacturer: "Raytheon / Lockheed Martin",
    era: "Modern (1996–present)",
    description: "Fire-and-forget anti-tank missile. Top-attack capability defeats any armored vehicle. \"Saint Javelin\" of modern warfare.",
    weight_kg: 22.3,
    effective_range_m: 2500,
    rate_of_fire: 1,
    damage_rating: 99,
    caliber: "127mm HEAT warhead",
    muzzle_velocity_ms: 290,
    capacity: 1,
    price_usd: 178000,
    action_type: "Fire-and-forget IR guided",
    tactical_score: 95,
    coolness_factor: 90,
    community_rating: 4.9,
    total_votes: 267,
    imageUrl: "/images/weapons/javelin.jpg",
    comparison_notes: "Equivalent to proton torpedo launcher - both are designed to take down heavily armored targets.",
  },
  {
    _matchKey: "combat-knife",
    name: "KA-BAR USMC Combat Knife",
    universe: "real",
    category: "melee",
    manufacturer: "KA-BAR",
    era: "1942–present",
    description: "The iconic fighting knife of the US Marine Corps. 7-inch blade, leather handle. Simple, deadly, legendary.",
    weight_kg: 0.32,
    effective_range_m: 2,
    rate_of_fire: 0,
    damage_rating: 45,
    tactical_score: 40,
    coolness_factor: 75,
    community_rating: 4.5,
    total_votes: 112,
    imageUrl: "/images/weapons/kabar-knife.jpg",
    comparison_notes: "The closest real-world analog to a lightsaber — both are melee weapons symbolizing warrior traditions.",
  },
];

// ============================================
// STAR WARS WEAPONS
// ============================================
export const starWarsWeapons: WeaponSeed[] = [
  {
    _matchKey: "e11-blaster",
    _equivalentKey: "m4-carbine",
    name: "E-11 Blaster Rifle",
    universe: "star-wars",
    category: "blaster",
    manufacturer: "BlasTech Industries",
    era: "Galactic Empire Era",
    description: "Standard-issue blaster of the Imperial Stormtrooper Corps. Reliable, mass-produced, and... famously inaccurate in the hands of Stormtroopers.",
    weight_kg: 2.5,
    effective_range_m: 300,
    rate_of_fire: 300,
    damage_rating: 65,
    energy_output_kj: 500,
    plasma_temperature_k: 8500,
    stun_setting: true,
    ammo_type: "Tibanna gas cartridge (100 shots)",
    tactical_score: 70,
    coolness_factor: 88,
    community_rating: 3.8,
    total_votes: 342,
    imageUrl: "/images/weapons/e11-blaster.jpg",
    comparison_notes: "Based on the real Sterling L2A3 submachine gun. Comparable to M4A1 in role. Plasma bolts travel at ~130 m/s vs bullets at 910 m/s — a massive disadvantage.",
  },
  {
    _matchKey: "dc15a-blaster",
    _equivalentKey: "m16a4",
    name: "DC-15A Blaster Rifle",
    universe: "star-wars",
    category: "blaster",
    manufacturer: "BlasTech Industries",
    era: "Clone Wars Era",
    description: "Standard-issue for Clone Troopers of the Grand Army of the Republic. More powerful and accurate than the E-11. The weapon that fought the Clone Wars.",
    weight_kg: 4.2,
    effective_range_m: 500,
    rate_of_fire: 260,
    damage_rating: 72,
    energy_output_kj: 750,
    plasma_temperature_k: 9200,
    stun_setting: true,
    ammo_type: "Power cell (500 shots)",
    tactical_score: 80,
    coolness_factor: 82,
    community_rating: 4.2,
    total_votes: 198,
    imageUrl: "/images/weapons/dc15a-blaster.jpg",
    comparison_notes: "Clone Trooper equivalent of M16. Better training = better accuracy. 500-shot capacity far exceeds 30-round magazines.",
  },
  {
    _matchKey: "dl44-blaster",
    _equivalentKey: "44-magnum",
    name: "DL-44 Heavy Blaster Pistol",
    universe: "star-wars",
    category: "blaster",
    manufacturer: "BlasTech Industries",
    era: "Galactic Civil War",
    description: "Han Solo's signature weapon. Illegally modified for extra power. \"Hokey religions and ancient weapons are no match for a good blaster at your side, kid.\"",
    weight_kg: 1.3,
    effective_range_m: 75,
    rate_of_fire: 30,
    damage_rating: 80,
    energy_output_kj: 350,
    plasma_temperature_k: 7800,
    stun_setting: false,
    ammo_type: "Power pack (25 shots)",
    tactical_score: 60,
    coolness_factor: 99,
    community_rating: 4.8,
    total_votes: 456,
    imageUrl: "/images/weapons/dl44-blaster.jpg",
    comparison_notes: "Named after the .44 caliber. Both are 'outlaw's weapons' - overpowered for their class. Han's DL-44 has illegal modifications, just like custom .44 Magnum loads.",
  },
  {
    _matchKey: "se14c-blaster",
    _equivalentKey: "glock-19",
    name: "SE-14C Blaster Pistol",
    universe: "star-wars",
    category: "blaster",
    manufacturer: "BlasTech Industries",
    era: "Galactic Empire Era",
    description: "Compact repeating blaster pistol used by Imperial officers. Reliable sidearm with rapid-fire capability. The 'gentleman's blaster'.",
    weight_kg: 0.8,
    effective_range_m: 40,
    rate_of_fire: 300,
    damage_rating: 48,
    energy_output_kj: 120,
    plasma_temperature_k: 6500,
    stun_setting: true,
    ammo_type: "Power cell (100 shots)",
    tactical_score: 65,
    coolness_factor: 60,
    community_rating: 3.5,
    total_votes: 89,
    imageUrl: "/images/weapons/se14c-blaster.jpg",
    comparison_notes: "The 'Glock of the Star Wars universe' - compact, reliable, nothing flashy. Standard officer sidearm.",
  },
  {
    _matchKey: "ee3-carbine",
    _equivalentKey: "barrett-m82",
    name: "EE-3 Carbine Rifle",
    universe: "star-wars",
    category: "blaster",
    manufacturer: "BlasTech Industries",
    era: "Galactic Civil War",
    description: "Boba Fett's favored weapon. Modified for extreme accuracy. \"He's no good to me dead\" — but with this rifle, targets are very dead at range.",
    weight_kg: 3.0,
    effective_range_m: 700,
    rate_of_fire: 20,
    damage_rating: 85,
    energy_output_kj: 900,
    plasma_temperature_k: 10000,
    stun_setting: false,
    ammo_type: "Tibanna gas (30 shots)",
    tactical_score: 82,
    coolness_factor: 96,
    community_rating: 4.7,
    total_votes: 301,
    imageUrl: "/images/weapons/ee3-carbine.jpg",
    comparison_notes: "Boba Fett's precision weapon. Like the Barrett, it's the elite marksman's choice. Both inspire fear by reputation alone.",
  },
  {
    _matchKey: "eweb-blaster",
    _equivalentKey: "m2-browning",
    name: "E-Web Heavy Repeating Blaster",
    universe: "star-wars",
    category: "heavy",
    manufacturer: "BlasTech Industries",
    era: "Galactic Empire Era",
    description: "Crew-served heavy weapon emplacement. Takes 15 minutes to set up. Devastatingly powerful once deployed. Seen on Hoth and the Death Star II.",
    weight_kg: 38.0,
    effective_range_m: 750,
    rate_of_fire: 120,
    damage_rating: 92,
    energy_output_kj: 3000,
    plasma_temperature_k: 12000,
    stun_setting: false,
    ammo_type: "Eksoan power generator",
    tactical_score: 75,
    coolness_factor: 78,
    community_rating: 3.9,
    total_votes: 134,
    imageUrl: "/images/weapons/eweb-blaster.jpg",
    comparison_notes: "The 'Ma Deuce' of the Star Wars galaxy. Both are crew-served weapons that dominate their engagement zones.",
  },
  {
    _matchKey: "bowcaster",
    _equivalentKey: "mossberg-500",
    name: "Wookiee Bowcaster",
    universe: "star-wars",
    category: "blaster",
    manufacturer: "Wookiee handcraft (Kashyyyk)",
    era: "Ancient – Present",
    description: "Chewbacca's signature weapon. Fires explosive energy quarrels using magnetic acceleration. Requires Wookiee strength to cock. Absolutely devastating.",
    weight_kg: 4.5,
    effective_range_m: 50,
    rate_of_fire: 8,
    damage_rating: 88,
    energy_output_kj: 1500,
    plasma_temperature_k: 11000,
    stun_setting: false,
    ammo_type: "Energy quarrels + tibanna gas",
    tactical_score: 60,
    coolness_factor: 93,
    community_rating: 4.5,
    total_votes: 267,
    imageUrl: "/images/weapons/bowcaster.jpg",
    comparison_notes: "Like a shotgun on steroids — close-range devastating power. Both are 'warrior's weapons' requiring strength and skill.",
  },
  {
    _matchKey: "proton-torpedo",
    _equivalentKey: "javelin",
    name: "Proton Torpedo Launcher",
    universe: "star-wars",
    category: "explosive",
    manufacturer: "Krupx Munitions",
    era: "Galactic Civil War",
    description: "The weapon that destroyed the Death Star. Guided energy torpedo that can hit a 2-meter exhaust port. \"Use the Force, Luke.\"",
    weight_kg: 45.0,
    effective_range_m: 5000,
    rate_of_fire: 1,
    damage_rating: 100,
    energy_output_kj: 500000,
    plasma_temperature_k: 50000,
    stun_setting: false,
    ammo_type: "Proton warhead",
    tactical_score: 98,
    coolness_factor: 97,
    community_rating: 4.9,
    total_votes: 389,
    imageUrl: "/images/weapons/proton-torpedo.jpg",
    comparison_notes: "Both are 'one-shot, one-kill' guided weapons designed to destroy heavily armored targets. The torpedo's Force-guidance is basically divine fire-and-forget.",
  },
  {
    _matchKey: "lightsaber",
    _equivalentKey: "combat-knife",
    name: "Lightsaber",
    universe: "star-wars",
    category: "lightsaber",
    manufacturer: "Jedi/Sith handcraft",
    era: "25,000 BBY – Present",
    description: "\"An elegant weapon for a more civilized age.\" Plasma blade contained by magnetic field. Cuts through virtually anything. Powered by kyber crystal.",
    weight_kg: 1.0,
    effective_range_m: 3,
    rate_of_fire: 0,
    damage_rating: 95,
    energy_output_kj: 20000,
    plasma_temperature_k: 25000,
    kyber_crystal_type: "Ilum crystal (various colors)",
    stun_setting: false,
    ammo_type: "Kyber crystal (infinite)",
    tactical_score: 45,
    coolness_factor: 100,
    community_rating: 5.0,
    total_votes: 999,
    imageUrl: "/images/weapons/lightsaber.jpg",
    comparison_notes: "Both represent warrior traditions and honor. Lightsaber plasma at 25,000K vs knife steel — no contest in power. But a .50 cal bullet moves at 900 m/s, and a lightsaber wielder needs Force precognition to deflect it.",
  },
  {
    _matchKey: "dc15s-blaster",
    _equivalentKey: "glock-19",
    name: "DC-15S Blaster Carbine",
    universe: "star-wars",
    category: "blaster",
    manufacturer: "BlasTech Industries",
    era: "Clone Wars Era",
    description: "Compact variant of the DC-15A. Better for close quarters. Clone Commandos and ARC Troopers preferred this for urban combat.",
    weight_kg: 2.1,
    effective_range_m: 200,
    rate_of_fire: 400,
    damage_rating: 60,
    energy_output_kj: 400,
    plasma_temperature_k: 8000,
    stun_setting: true,
    ammo_type: "Power cell (300 shots)",
    tactical_score: 78,
    coolness_factor: 75,
    community_rating: 4.0,
    total_votes: 167,
    imageUrl: "/images/weapons/dc15s-carbine.jpg",
    comparison_notes: "The compact carbine version — like going from M16 to M4. Clone Commandos used it the way SOF uses PDWs.",
  },
];

// ============================================
// HELPER: Get all weapons for seeding
// ============================================
export function getAllWeapons(): WeaponSeed[] {
  return [...realWeapons, ...starWarsWeapons];
}

// ============================================
// HELPER: Get matched pairs for comparison
// ============================================
export function getComparisonPairs(): Array<{ realKey: string; sciFiKey: string; realName: string; sciFiName: string }> {
  const pairs: Array<{ realKey: string; sciFiKey: string; realName: string; sciFiName: string }> = [];
  
  for (const sw of starWarsWeapons) {
    if (sw._equivalentKey) {
      const real = realWeapons.find(r => r._matchKey === sw._equivalentKey);
      if (real) {
        pairs.push({
          realKey: real._matchKey,
          sciFiKey: sw._matchKey,
          realName: real.name,
          sciFiName: sw.name,
        });
      }
    }
  }
  
  return pairs;
}

// ============================================
// HELPER: Get full weapon objects for comparison pairs
// ============================================
export function getComparisonPairsFull(): Array<{ sciFi: WeaponSeed; real: WeaponSeed }> {
  const pairs: Array<{ sciFi: WeaponSeed; real: WeaponSeed }> = [];
  
  for (const sw of starWarsWeapons) {
    if (sw._equivalentKey) {
      const real = realWeapons.find(r => r._matchKey === sw._equivalentKey);
      if (real) {
        pairs.push({ sciFi: sw, real });
      }
    }
  }
  
  return pairs;
}
